### PR TITLE
Uaa pagination of orgs and spaces

### LINKED ISSUE #39: Fix pagination for UAA for users with over 100 spaces/orgs (1/7)
In order for a user who(m) has roles in over 100 spaces and organizations, we want to be able to successfully paginate requests to allow them access to the logs for all of the spaces and orgs they belong to on not just the first 100.

## Acceptance Criteria
* [ ] GIVEN an authenticated user has access to all of the logs for all of their spaces and orgs.

## Security considerations
none

## Implementation sketch
[links to background notes, sketches, and/or relevant documentation
* [ ] Update logic in https://github.com/cloud-gov/logsearch-for-cloudfoundry/blob/develop/src/kibana-cf_authentication/server/uaa-provider.js
* [ ] Successfully paginate orgs and spaces when greater than 100.

### PR DESCRIPTION
**Pull request by apburnes**
Fixes #39 

Adds helper functions for v2 and v3 (only using v2 api for now) of the API to query orgs and spaces for a user and paginate through the endpoint pages when a user has more results than the per page amount. Currently users with more than 100 roles in spaces and orgs do not get access to the logs passed those first 100.

## Acceptance Criteria
- [x] When a user has more than spaces/orgs than the api result amount per page, the paginator will request each next page from the API until there are no more pages of results.
- [x] Added some local testing based on the data structure of the v2 and v3 api to test pagination locally first.

## Security Considerations

None

### Note
The v3 api has a page size limit of 5000 records.  We could bump up the v3 `per_page` of 100 in the url query param to minimize the number of paginated requests.

### CODE REVIEW

**Review by bengerman13 — DISMISSED** [review]
LGTM, with two catches:
- PR needs a `security considerations` section
- we should get this out before @spgreenberg moves forward with his merge, or after he gives an all-clear on it

**Comment by bengerman13** [comment]
also if this works, we should send it upstream and link it to cloudfoundry-community/logsearch-for-cloudfoundry#338

**Comment by spgreenberg** [comment]
Sorry, I had already merged the 211 changes.

**Comment by bengerman13** [comment]
no worries @spgreenberg - the big thing I was trying to avoid was merging this right as you merged yours, which is still very avoidable.

**Review by bengerman13 — APPROVED** [review]

**Pull request merged**
